### ISSUE TITLE
Mobile data usage

### ISSUE THREAD

**Issue by htetoh** [aashishksahu/SafeSpace#15]
![Screenshot_20230926-090542_Settings](https://github.com/aashishksahu/SafeSpace/assets/70825624/68bf84cd-a5b3-40e4-81ac-b2f99658512f)
 
I downloaded from github using obtainium.
Why app is using 55.66 KB of mobile data.

**Comment by aashishksahu** [comment]
Hmm... that's an interesting situation. There's no internet connectivity in my app.
I'll need a little more information. Can you please install pcapdroid and check which domains my app is connecting to.
It could be false information or maybe you clicked a link on the about page. It will be very helpful if you can do a network log using pcapdroid which is available on fdroid store. 
I have seen the same thing happen with keepassdx but it also doesn't have internet connectivity.

**Comment by htetoh** [comment]
> Hmm... that's an interesting situation. There's no internet connectivity in my app. I'll need a little more information. Can you please install pcapdroid and check which domains my app is connecting to. It could be false information or maybe you clicked a link on the about page. It will be very helpful if you can do a network log using pcapdroid which is available on fdroid store. I have seen the same thing happen with keepassdx but it also doesn't have internet connectivity.

Yes I clicked a link from about page.
I turned on ultra data saver mode already.
And 
I noticed that app is used 55.66 KB. 

I installed Pcapdroid and tested on app.
Most connections are fairEmail and NextDNS.

 Here

![Screenshot_20230926-112948_PCAPdroid](https://github.com/aashishksahu/SafeSpace/assets/70825624/311e2f48-f091-4a90-858e-bdba95b39f26)

It's no more using.

I will report here when something new.

**Comment by aashishksahu** [comment]
Yeah this happens, a lot of times android system attributes false data usage information to apps that don't even have internet permissions. [Similar issue observed in KeepassDX](https://www.reddit.com/r/KeePass/comments/tzmo7n/why_is_keepassdx_using_mobile_data/?rdt=35686) suggests that the app config is being backed up or something. One more thing if you can please check, is this app showing up in the google drive backup? If yes, then that's an issue to be resolved, because data inside this app is not supposed to be backed up to google drive. 

Rest assured as I don't make any money from this app, so I don't have any servers logging user data. I mean I have no use for that data as I don't intend to sell it and get into legal trouble since PR and lawyers are way too expensive, lol. I also don't show any ads so no revenue from there and I have already written in the disclaimer that targets of the govt need not install the app, so can't sell data to the govt either :)

**Comment by htetoh** [comment]
> Yeah this happens, a lot of times android system attributes false data usage information to apps that don't even have internet permissions. [Similar issue observed in KeepassDX](https://www.reddit.com/r/KeePass/comments/tzmo7n/why_is_keepassdx_using_mobile_data/?rdt=35686) suggests that the app config is being backed up or something. One more thing if you can please check, is this app showing up in the google drive backup? If yes, then that's an issue to be resolved, because data inside this app is not supposed to be backed up to google drive.
> 
> Rest assured as I don't make any money from this app, so I don't have any servers logging user data. I mean I have no use for that data as I don't intend to sell it and get into legal trouble since PR and lawyers are way too expensive, lol. I also don't show any ads so no revenue from there and I have already written in the disclaimer that targets of the govt need not install the app, so can't sell data to the govt either :)

Maybe It's made by Google play services since i disabled Google drive.
Like KeepassDX issue.
Thanks for your time.
