### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by mtris** [aashishksahu/SafeSpace#20]
Hello SafeSpace Team: Congrats on making a fun powerful app.
My feature request is: Settings to change app colors. If not the ability to personalize all the colors, maybe just a dark/night/black mode? Thank you for your time and for making a privacy-focused app.
Sincerely,

**Comment by aashishksahu** [comment]
Thanks @mtris for reaching out. I'll plan something for this feature :) Thanks for using my app.

**Comment by aashishksahu** [comment]
Hi @mtris, I've been trying to find a way to implement multiple color themes but haven't been lucky so far, it seems implementing custom styles will call for a major code change which may not be feasible as of now due to time constraints and other professional commitments. Hopefully, in the future, If I get more contributors, I might be able to implement this feature. Thanks for reaching out though :)

**Comment by mtris** [comment]
Hi @aashishksahu thanks for the reply. Very understandable. Nicely done on on the dark theme! I sent you a PP to the email address you have listed on this page. Hope things keep going great.-Tristan

**Comment by aashishksahu** [comment]
Hi @mtris Thanks for the generous response and the PayPal, but I can't accept it because my goal with this app was to create software that protects user privacy and I want to deliver a full app with all the features without any paywalls. This app is a side project that I believe is a necessary contribution towards combating the reign of big tech and their malicious ways of business. Therefore, I thank you for your Paypal, it means a lot to me and keeps me motivated to work on this project but I'll not be able to accept it :)
