### ISSUE TITLE
Adding functions

### ISSUE THREAD

**Issue by atomuspilius** [aashishksahu/SafeSpace#22]
Hello! Thank you for this app!

If possible, please add:

1. Make it possible to select file sorting [name/date/type] ✅
2. Make it possible to move several selected files between folders at the same time. ✅
3. Make it possible to copy/move folders and/or unpack the ZIP to a specific folder, not just the root one. ✅

Thanks!

**Comment by aashishksahu** [comment]
Thanks for using my app! I'll check the feasibility of these features and plan the next release accordingly. Thank you for the suggestions :)

**Comment by aashishksahu** [comment]
Will close the issue once I merge a pull request :)

**Comment by Ujjwal990524** [comment]
Please add option to set different password other than screen lock then it will more secure

**Comment by aashishksahu** [comment]
@Ujjwal990524 Thanks for the suggestion, I also thought of this when I was designing the app. If we add a separate password, it indicates that the contents of the app are to be encrypted with this password (explained in the readme why I am avoiding this). Now, let's say we add a password just to authenticate the user to use the app (similar to a login), in that case, we will have to compare the user entered password to a stored password. Now here's the issue, how does one store password securely. The only proper way to store passwords is to encrypt them, which brings us back to square one, another password to encrypt the password used to login to the app. Another way is to use system secure storage method such as keychain. This will again require you to store keys in the system which will require screen lock to access. Everything on an android phone is encrypted using your screen lock. That's why, I used screen lock to authenticate(I am also a noob, please correct me if I missed something). 

Maybe in the future If I had more dedicated contributors (less likely for a FOSS app that has no revenue generation and marketing, but hoping...), I am aiming to completely move to Veracrypt containers, it's going to require a lot of time and research. Not committing to that today though. Hopefully, I have answered your question, thanks for reaching out :)

**Comment by myryk31415** [comment]
Hey :)

first of all great app! really like it.

+1 for selecting multiple files for copying, deleting etc and moving folders.

Another problem i have is that upon importing
photos they all have the date of import instead of the original date. I had that problem in every "save folder" app so far, so idk if its even fixable. One workaround tho is putting them in a compressed folder, importing and then extracting. So a great feature would be

- de- and compressing folder

Thanks for ur awesome work tho :D

**Comment by aashishksahu** [comment]
@myryk31415 Thank you so much for the kind words! Really means a lot. Compressing and decompressing folders is already in the roadmap above. Also, when we import a photo it makes a copy of the original photo, so this copy will have the date and time when it was created because it is a new file for the system. But as you said compressed folder might just work :)

**Comment by myryk31415** [comment]
ah okay i thought it was just about the import backup feature, which also changes the date of the files. But thats great to hear. And yes decrompressing a zip folder fixed it for me in a similiar app. Have a great day :)
