### ISSUE TITLE
App crashes after password

### ISSUE THREAD

**Issue by Xzld** [aashishksahu/SafeSpace#46]
The app now crashes everytime i try to unlock it. I tried clearing cache and it did nothing. I think i might have uploaded a corrupt file and it is trying read it. Please help. I couldnt back up my data. I deleted the imported files and was about to create a zip backup. Now im lost without my data.

**Comment by aashishksahu** [comment]
Hi @Xzld, I am sorry to hear that, let’s figured this out. Clearing cache will not do much as I am not using cache in my app, corrupt file also shouldn’t be an issue as it’s just a file. Please help me with a few more details. 
device model:
OS version:
What type of screen lock you’re using:
Have you setup the app pin:
Was it working in a previous version(which one):
At what step exactly the app crashes:

**Comment by Xzld** [comment]
Device model: samsung m31
Os: android 12
Pin and fingerprint
Yes
 Yes it was working with the previous version(1.4.3) of the app

I was uploading a few videos to the app and it crashed halfway through upload. I couldnt open the app ever since. I can enter my pin but the app stops responding afterwards.

**Comment by aashishksahu** [comment]
This is a weird issue, Since I don't have any diagnostics telemetry in this app, pointing out the exact cause would be difficult. Here's a workaround:
1. Go to [this link](https://developer.android.com/tools/releases/platform-tools) and download platform tools for your desktop or laptop.
2. Unzip it and open terminal/powershell in that folder (on windows 11 and linux you can right click and open with terminal).
3. Now go to your phone's settings and go to "About phone", and then tap "Software information", then rapidly tap "Build number" until developer options are turned on.
4. Then go back and go to developer options and enable usb debugging and connect your phone to pc using a usb cable.
5. Go to the terminal you opened and type `adb devices`. A prompt will pop up on your phone asking for usb debugging permission. Press Allow.
6. now type `adb devices` again and you will see 1 entry under `List of devices attached`,  this means that your phone is successfully connected to usb debugging using adb.
7. Next, download v1.4.4 from [this link](https://github.com/aashishksahu/SafeSpace/blob/281ff169987e79ed09739094f2f07189f71bdb96/app/release/app-release.apk)
8. place this apk in the platform-tools folder and type `.\adb.exe install -d app-release.apk`. This will install v1.4.4 without deleting the data.

Let me know if you can then open the app. You can also take a backup of your data and then reinstall the app.

**Comment by Xzld** [comment]
Unfortunately this did not fix the issue.

**Comment by aashishksahu** [comment]
can you, if possible, try to import that same file in some other phone? let me know what happens.

**Comment by Xzld** [comment]
Hey, good news! I figured out the problem. Turns out I had two files with a similar name. One file was "whatever(1).jpg" and the other was "whatever (1).jpg"
When I import both to the app it crashes. Perhaps your app isn't reading spaces?

**Comment by aashishksahu** [comment]
Good to hear that your issue is resolved, I'll surely test and fix this bug, although these two file names are different, but anyway, I'll check it. Thanks :)

**Comment by aashishksahu** [comment]
Hmm… I would suggest that you wait for the next update, hopefully I’ll figure something out…

**Comment by aashishksahu** [comment]
hi @Xzld , Good news! I figured out the problem and have pushed a fix. Will release the apk soon. Thanks for your detective work on the naming issues.

**Comment by Xzld** [comment]
Great!, looking forward to it.

**Comment by Xzld** [comment]
No updates yet?

**Comment by aashishksahu** [comment]
Yeah…. Been a little busy with work, will try to release an update this weekend.
