### ISSUE TITLE
Adding folders doesn't work?

### ISSUE THREAD

**Issue by GameOverFlowChart** [aashishksahu/SafeSpace#6]
It seems like I can only add files. Would be nice if we could add a whole folder structure.

Not sure if it's worth a new issue but I also tested the app with images and it seems like you can't simply swipe through images in the image viewer.

**Comment by aashishksahu** [comment]
Thanks for using Safe Space, feedback is much appreciated. Both of these points can be feature requests, not sure about importing an entire folder, need to check feasibility. I will revert back here after my analysis.

**Comment by aashishksahu** [comment]
So, for "adding a folder" functionality, it might not be possible since Android's file picker doesn't offer any standard way to import an entire folder using a file picker, therefore, it might not be possible to implement that, but you can create a folder in the app and select all the files you want to import as the file picker has multiple selection possibility. 

Coming to swipe gesture for images, it seems to be doable, but will require some serious rewrite, will target this in the next major release.

**Comment by GameOverFlowChart** [comment]
What about asking access to a folder via storage access framework, similar how NewPipe asks for a folder to save files in it? The difference to NewPipe would be that the access would only be needed temporaryly to read what's inside. In case of NewPipe, Android allows to pick a folder instead of a file.

**Comment by aashishksahu** [comment]
I thought of this too, but I am not sure if it's a reliable solution, the user will see that the app is requesting access to a directory, even if I am not persisting the access, the user will perceive it as such. It's doable but doesn't feel like an elegant solution. Maybe if you are willing to create a pull request with a proof of concept, we can see how it would pan out.

**Comment by GameOverFlowChart** [comment]
I understand and also don't know if there is a way to release that access right. An alternative aprouch would be using the share/send function so that I can send a folder from my file manager to the app but I'm not sure if sending a folder keeps the folder structure inside of it intact or just sends all the files in it. I would need to look into this.
