### ISSUE TITLE
[Feature Request] Backup scheduling

### ISSUE THREAD

**Issue by W1zardK1ng** [aashishksahu/SafeSpace#67]
To add little convenience it will be good to have an option to schedule backups, like auto backup at everyday 2 am or so.
Also to avoid creating lots of backup file, add an option to limit the max number of backup files to keep.

**Comment by aashishksahu** [comment]
I thought of this too but imagine someone having 15 gb of data stored in the app, it will simply eat the storage even if I had two backups, scheduled backups work well for messaging apps because the size of the data is usually small, but since, my app's main focus is data of all sizes, so it won't be possible to add this feature and having an optional feature that not a lot of people will enable because of storage issue then the development efforts will be in vain. Currently my focus is on something working and stable. Thanks for the suggestion though, much appreciated :)
