### ISSUE TITLE
How is the app better than droidfs?

### ISSUE THREAD

**Issue by Wjxfi** [aashishksahu/SafeSpace#8]
it's important to know. I think that app is safer and more proven.

**Comment by aashishksahu** [comment]
Although DroidFs is a good option and is mature, the two apps in question use different approach to store files. Droidfs uses gocryptfs as a file system which has encryption capabilities. But I believe that on an android 11+ phone it is a bit redundant to encrypt files if you are storing them in the app's internal storage. As per my observation, when you create a vault in DroidFs, it encrypts all the files before storing them in an already encrypted location (the app-specific storage). 

Now, two things are happening, first, the app is performing encryption operations which do use processing power, therefore, consuming battery and second, every operation performed on a file has the possibility to fail due to plenty of reasons such as an OS deadlock, I/O problems, external operations conflicting with the app's operations etc. 

In terms of security, droidfs has solid and proven encryption scheme but also opens certain vulnerabilities that may be existing in gocryptfs or the android implementation of it, since android doesn't use mountable file systems like desktops os does.

I believe mobile apps should be simple, fast and power efficient, therefore, DroidFs, although it's a remarkable implementation of gocryptfs for android, comes with potential pitfalls such as redundant operations and can carry forward the problems already existing in gocryptfs. 

Safe space on the other hand reduces redundancy and prefers simplicity, which results in faster performance and power efficiency. Surely, the app is in it's early stages so there's more optimisation to do but I believe both apps have a good potential to develop and can cater to the needs of the privacy conscious :)

**Comment by aashishksahu** [comment]
Security isn't a linear scale where something is "more" or "less" secure. Security vulnerabilities can arise from all directions, whether it is a network based attack, a hardware based attack, freezing the ram and stealing it, physical attacks on the user, all kinds of things are possible. Security isn't just about the patches or updates you install. 

As for whether my app being less secure, if your choice of app encrypts a file twice and that translates to being the app "more" secure, then, yes my app is "less" secure, just like locking a door with a padlock and locking the padlock again with another padlock is "more" secure than locking the door with just a single padlock.

Surely, there are some things that definitely need to be encrypted such as contents of a password manager and device keys, but my app is meant for people who just want a file manager where the files are not globally accessible by other apps, because your phone is mostly the apps you use and apps do have a possibility to collect metadata of the files stored in common, globally available directories (not accusing anyone here, just quoting a possibility).

But if we look on the other side, a lot of people would give up security because it's not convenient and easy to use, a lot of people don't use a password manager (which they should btw). Giving them one more password to remember will drive them away from making a choice that favours the privacy of their data.

Coming to cryfs, on their website, they literally have a page where they are pointing out the problems with other even more tested and proven applications like Veracrypt [Link to the article](https://www.cryfs.org/comparison), according to this article, every other product is good but their product is better (that's marketing 101). 

At last, I would suggest that, please don't think of security as just a code and software thing, and apps aren't just made for tech-savvy people. In fact, it is the duty of the tech savvy to make tech easier for other people.

**Comment by aashishksahu** [comment]
I understand the need for encryption and I agree with you, but there are a few reasons why I haven’t encrypted everything:

1. Security audits are expensive, and these must be done every year to stay compliant, without an audit or a pen test the encryption is only good on paper
2. I’d prefer relying on device encryption rather than something I cook up. Let’s say I implement encryption, now where would I store the key after decryption and what about when the user says that they find it inconvenient to unlock the app every time with a master password, moreover, if I use the keychain and biometric to generate and store the keys them we are basically relying on device encryption.
3. I am not saying encryption is impossible, it’s just that it will require a lot of expertise and testing, in other words, time and money.

I love encryption but, building something that isn’t thoroughly tested is no better than not using encryption at all. That’s why we use veracrypt and gpg and not jojo’s bizzare encryption tool. But thanks for sharing your ideas, I appreciate it.

**Comment by aashishksahu** [comment]
Good news, I have already implemented this root check feature :)
